### ISSUE TITLE
kernel version: update to latest stable

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/linux#1]
We are currently sat on 4.12.4, but the latest stable today is 4.13.13. If we are tracking the latest stable at present, then we need to update to 4.13.13.

Longer term (pun intended), if we are going to track a longterm rather than a stable kernel version, then we probably want to wait for the next longterm (which is 4.14 iirc), which has only just been released, and thus will take a little while (a month or two?) to settle down into a longterm I think.

**Comment by devimc** [comment]
https://github.com/kata-containers/linux/tree/linux-kata-containers-4.13.3

**Comment by sameo** [comment]
cc @gnawux @laijs @bergwolf Are you guys ok moving to 4.13.13? 4.12.4 seems to not be a stable maintained kernel.

**Comment by gnawux** [comment]
OK to move to new upstream versions.

And which version will become the next LTS? 4.14?

2017年11月17日 08:22，"Samuel Ortiz" <notifications@github.com>写道：

cc @gnawux <https://github.com/gnawux> @laijs <https://github.com/laijs>
@bergwolf <https://github.com/bergwolf> Are you guys ok moving to 4.13.13?
4.12.4 seems to not be a stable maintained kernel.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kata-containers/linux/issues/1#issuecomment-345106569>,
or mute the thread

**Comment by bergwolf** [comment]
Yes, the next LTS stable kernel is 4.14. I agree we can settle with 4.13 for now and move to 4.14 later.

**Comment by sameo** [comment]
@bergwolf @gnawux Thanks, master is updated to 4.13.13, and I created a branch for our 4.13.13 based kernel.

**Comment by grahamwhaley** [comment]
I'll close this issue then. We can open a new one when we agree it is time to move to 4.14.
